title: Civic Engagement Platform
description: A platform for addressing civic issues across India's 19,101 PIN codes
theme: just-the-docs

url: https://kushalkmrd.github.io/mpga_draft

# Color scheme
color_scheme: light

# Enable search
search_enabled: true

# Enable copy code button
enable_copy_code_button: true

# Footer content
footer_content: "Copyright &copy; 2024 Civic Engagement Platform. Distributed by an <a href=\"https://github.com/kushalkmrd/mpga_draft/blob/main/LICENSE.txt\">MIT license.</a>"

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/kushalkmrd/mpga_draft"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"


# Aux links for the upper right navigation
aux_links:
  "GitHub Repository": "https://github.com/kushalkmrd/mpga_draft"

# Makes Aux links open in a new tab
aux_links_new_tab: true

# Optimize for SEO
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false